GPU available: False, used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
Found cached dataset glue (/home/codespace/.cache/huggingface/datasets/glue/cola/1.0.0/dacbe3125aa31d7f70367a07a8a9e72a5a0bfeb5fc42e75c9db75b96da6053ad)
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 707.10it/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:00<00:00, 13.26ba/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 24.78ba/s]
  | Name                   | Type                          | Params
-------------------------------------------------------------------------
0 | bert                   | BertForSequenceClassification | 4.4 M
1 | train_accuracy_metric  | BinaryAccuracy                | 0
2 | val_accuracy_metric    | BinaryAccuracy                | 0
3 | f1_metric              | BinaryF1Score                 | 0
4 | precision_macro_metric | BinaryPrecision               | 0
5 | recall_macro_metric    | BinaryRecall                  | 0
6 | precision_micro_metric | BinaryPrecision               | 0
7 | recall_micro_metric    | BinaryRecall                  | 0
-------------------------------------------------------------------------
4.4 M     Trainable params
0         Non-trainable params
4.4 M     Total params
17.545    Total estimated model params size (MB)
/home/codespace/.python/current/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:224: PossibleUserWarning: The dataloader, val_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 4 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
/home/codespace/.python/current/lib/python3.10/site-packages/pytorch_lightning/utilities/data.py:85: UserWarning: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 64. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
  warning_cache.warn(
Sanity Checking DataLoader 0: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00,  8.56it/s]
/home/codespace/.python/current/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:224: PossibleUserWarning: The dataloader, train_dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 4 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
















Epoch 0:  89%|██████████████████████████████████████████████████▌      | 134/151 [00:38<00:04,  3.50it/s, loss=0.61, v_num=v9b0, train/loss_step=0.617, train/acc_step=0.692]

Validation DataLoader 0: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 17/17 [00:01<00:00,  9.10it/s]
/home/codespace/.python/current/lib/python3.10/site-packages/pytorch_lightning/utilities/data.py:85: UserWarning: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 19. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
  warning_cache.warn(


















Epoch 1:  97%|▉| 147/151 [00:41<00:01,  3.56it/s, loss=0.601, v_num=v9b0, train/loss_step=0.516, train/acc_step=0.795, valid/loss_step=0.485, valid/loss_epoch=0.618, valid/a

Validation DataLoader 0:  76%|████████████████████████████████████████████████████████████████████████████████████▉                          | 13/17 [00:01<00:00,  9.36it/s]


















Epoch 2:  90%|▉| 136/151 [00:39<00:04,  3.47it/s, loss=0.593, v_num=v9b0, train/loss_step=0.655, train/acc_step=0.641, valid/loss_step=0.487, valid/loss_epoch=0.618, valid/a

Validation DataLoader 0: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 17/17 [00:01<00:00,  9.11it/s]

`Trainer.fit` stopped: `max_epochs=3` reached.